name: ldt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  dio: ^5.1.1
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  badges: ^3.1.1
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/bar/
    - assets/images/